### ISSUE TITLE
Input issue in Termux

### ISSUE THREAD

**Issue by notgne2** [SinuXVR/pocket-board#1]
I'm glad I found this project and it has been working very well, however I've been unable to use this with the Termux app. Every key I press results in Termux just entering a new line instead of whatever key I press (though I have only tested this on the initial bash prompt), whereas with other IMEs it functions as expected.

I'm not sure if this issue only affects me as I'm running a GSI ROM on my Titan Pocket instead of the stock ROM, and this causes various input differences, even when copying the icd/kl/kcm files extracted from the stock ROM. The main difference I've noticed is that the modifier keys (shift/alt) do not function on certain input field types when using other IMEs (Blackberry, Kika), interestingly using this IME actually solves this issue, I'm not sure if this is related to the Termux issue but it at least seems to me that it might be (though I know basically nothing about input devices from the Android side, and my only wrangling with it on this device has been with uinput).

side note note, another thing using a GSI ROM as opposed to the stock ROM causes is the SYM key bringing up the input method selector regardless of IME selected, so if you know how to solve that I'd really appreciate it if you let me know :)

**Comment by SinuXVR** [comment]
Hi, thanks for the info! I have checked and can confirm that this problem occurs on standard ROM as well, because the Termux console does not work like a regular text editor field. However I made some fixes and it seems like everything is working now. Please try the new [v1.1.2 release](https://github.com/SinuXVR/pocket-board/releases/tag/v1.1.2).

Regarding SYM key problem, it's out of my control :( Stock ROM also has this  feature, but it is binded to SYM+ALT and SHIFT+SYM. It seems like there is no way to change it :(

**Comment by notgne2** [comment]
That seems to fix most of it, even allows me to push Alt or Shift ahead of the key. However only symbols seem to be inputting with the Alt key, if I try any of the keys associated with numbers nothing gets inputted.

As for the SYM issue I have now came across [this](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/view/inputmethod/InputMethodManager.java#2586) as well which seems to confirm there's not much I can do without compiling the GSI from source, but would it instead be possible if you made pocket-board accept a different keycode as well as KEYCODE_SYM, then I can update my keylayout file to use that keycode instead?

**Comment by SinuXVR** [comment]
Hmm, I can't reproduce the Alt bug, I can print any symbols and digits using Alt key or long press... What version of the Termux do you use?

For the SYM issue, I will add a way to use some other key code with no problem

**Comment by notgne2** [comment]
Is there any logs I can provide to help? Long press, Alt at the same time, or Alt ahead of a key with a symbol all work perfectly, inputting a number with the on screen button works fine too, but if I try to input a number it doesn't work, no key gets entered no matter how I try it and the keyboard ends up in a normal state (as in, the next key doesn't get symbolized or anything), and if I long press then the original character gets deleted but no number replaces it.

**Comment by SinuXVR** [comment]
Could you check [this](https://dropmefiles.com/aEZbD) build please? Archive password is 123

**Comment by notgne2** [comment]
@SinuXVR that works perfectly!

**Comment by SinuXVR** [comment]
So I've released a new version [1.1.3](https://github.com/SinuXVR/pocket-board/releases/tag/v1.1.3) with fixes. Also you can use [KEYCODE_PICTSYMBOLS](https://developer.android.com/reference/android/view/KeyEvent#KEYCODE_PICTSYMBOLS) as an alternative to [KEYCODE_SYM](https://developer.android.com/reference/android/view/KeyEvent#KEYCODE_SYM) now, they both act the same

**Comment by notgne2** [comment]
Thanks! Termux and the `sym` button work perfectly now, though I've messed up my KCM files so I'll have to fix those now (I'm planning on uploading a Magisk module that includes all of the system level fixes I've made to let this device work well without the stock ROM)
