### ISSUE TITLE
Doesn't work on Android 11 on Unihertz Titan Slim

### ISSUE THREAD

**Issue by Izaic** [SinuXVR/pocket-board#4]
The Titan Slim comes with Android 11, but this app doesn't seem to work properly on it. It doesn't show as a keyboard app, and there's no option to launch it like a normal app either.

**Comment by SinuXVR** [comment]
Hi, it looks like you forgot to turn it on. Go to Settings > Language & Input > On-screen keyboard > Keyboard management and toggle the switch

**Comment by Izaic** [comment]
That was it! Sorry!
